### ISSUE TITLE
lowering minimal android version to 4.0?

### ISSUE THREAD

**Issue by roytam1** [kitsunyan/foxy-droid#10]
it will be nice if this will work on older devices.

**Comment by kitsunyan** [comment]
Definitely no. It's PITA to support older Android versions especially if the application was initially designed for 5+. I mean, I'll have to rewrite about 50% of the application, adding a lot of compatibility code here and there.

**Comment by roytam1** [comment]
> Definitely no.

alright got it

**Comment by Spielmops** [comment]
I use for my Kikat-Device Fdroid 0.102.3

**Comment by kitsunyan** [comment]
@Spielmops you can try [F-Droid Classic](https://gitlab.com/Bubu/fdroidclassic), which is a good alternative and it works on 4.4. At least, it's supported (for instance, it supports new index and addresses some issues of old F-Droid). I don't recommend 0.102.3, it's very slow and laggy when you sync repositories.

**Comment by Spielmops** [comment]
Thanks for this information, but - my fault - it's Android 4.2 on my old phone and that is "Jelly Bean". The classic version doesnct work with 4.2 ...

Spielmops
