### ISSUE TITLE
Sort by updated

### ISSUE THREAD

**Issue by PacoBell** [kitsunyan/foxy-droid#11]
It's it just me or is there currently no way to sort the apps list by the time updated? If not, could we do that? That's pretty much the only thing keeping me from using this as my "daily driver".

**Comment by roytam1** [comment]
> It's it just me or is there currently no way to sort the apps list by the time updated? If not, could we do that? That's pretty much the only thing keeping me from using this as my "daily driver".

did you try version 1.1?
