### ISSUE TITLE
Back button quits app even if drop down list is opening

### ISSUE THREAD

**Issue by roytam1** [kitsunyan/foxy-droid#12]
I think users don't intend to close app when drop down list is opening but just want the list be closed when pressing Back button.

**Comment by kitsunyan** [comment]
Nice catch. I'll fix that.

**Comment by kitsunyan** [comment]
Fixed in https://github.com/kitsunyan/foxy-droid/commit/ba3936311e29e71e044e96d2fe23f6324b6f93dd
