### ISSUE TITLE
Sorting Method

### ISSUE THREAD

**Issue by Qyrln** [kitsunyan/foxy-droid#13]
Hello,Dev
Sorting method is automatically reset to "sort by name" every time , i reopen foxy droid .
Can you make the sorting method permanent ?

**Comment by tanrak** [comment]
Remember the sorting method would be awsome.

**Comment by kitsunyan** [comment]
Done https://github.com/kitsunyan/foxy-droid/commit/6866a049326dad7bfdd1ba6f9efc887cf5e5dcda

**Comment by tanrak** [comment]
Thanks a lot.
