### ISSUE TITLE
Going back focuses search bar

### ISSUE THREAD

**Issue by ThatsJustCheesy** [kitsunyan/foxy-droid#19]
Pressing the back button while viewing an app goes back to the app list, as expected. However, it also auto-focuses the search field, which is annoying when I'm just trying to browse the list. I don't think it should do this, or perhaps it should only do this if the search field was already focused before the context switch.

Thanks for this clean client :)

**Comment by kitsunyan** [comment]
Fixed in https://github.com/kitsunyan/foxy-droid/commit/930e19577210710e72e49eeec242928f368f35a4
