### ISSUE TITLE
Crashed on start

### ISSUE THREAD

**Issue by sunng87** [kitsunyan/foxy-droid#2]
Foxy droid crashed on my Oxygen OS Android 10. I have got this log and wish it's useful to you.

![image](https://user-images.githubusercontent.com/221942/84016109-62317200-a9af-11ea-8a12-fd1f84d24db3.png)

**Comment by kitsunyan** [comment]
Meh. I didn't expect that.
Don't you mind if I just post APK here? I'd preferred to not make any releases until application will be accepted to the main F-Droid repository.

(GitHub doesn't allow attaching APK files, just rename it.)
[foxy-droid-release.apk.zip](https://github.com/kitsunyan/foxy-droid/files/4745280/foxy-droid-release.apk.zip)

**Comment by sunng87** [comment]
My APK was downloaded from github release page.
