### ISSUE TITLE
Low contrast title

### ISSUE THREAD

**Issue by andinus** [kitsunyan/foxy-droid#23]
The title on top left bar is gray-ish, makes it harder to read on dark blue-ish background.

Foxy Droid v1.1 06/07/2020

Screenshot: https://ttm.sh/Qlx.jpg

**Comment by kitsunyan** [comment]
Which Android version?

**Comment by andinus** [comment]
This is on Android 10. All screens are affected, Light/Dark theme don't affect it.

**Comment by kitsunyan** [comment]
I tried on Android 10 emulator, and text color is white.

Unfortunately, I don't have Samsung device to reproduce this problem (I also don't know anything about how different modern Samsung devices). Does you device have something like theming engine and do you use some non-standard theme in this case? Do you experience this problem when you're using the light theme instead of the dark one (I mean application theme which is configurable in preferences)? Do you use night mode, or something like that?

**Comment by andinus** [comment]
There was a theming application, I haven't used it so this is stock One UI. 

Here's how it looks in light theme:
![Screenshot_20200721-213722_Foxy Droid](https://user-images.githubusercontent.com/62012039/88078710-4bfd0100-cb6c-11ea-95d2-28ad7339aed7.jpg)

There is a system dark mode which I don't believe affects other applications. AFAIK it's an option that applications can check for automatic theming, something like `@media color-prefers` (CSS). I tried with the default (light mode) too & it's still the same.

Looking from naked eyes, looks like the font color is same as the dark background color. Is there some `!important` thing that you can add on font color?

**Comment by kitsunyan** [comment]
No, it's a different color. Probably it comes somewhere from default colors of light theme, or something else.

I think I can try to make a testing application so you could run it and check the colors with different configuration, so I could be able to understand why this happens.

**Comment by andinus** [comment]
kitsunyan @ 2020-07-21 22:06 IST:

> I think I can try to make a testing application so you could run it
> and check the colors with different configuration, so I could be able
> to understand why this happens.

I see, yeah I could test it. If possible, make it so that I can install
it alongside the real Foxy Droid application (different signature ?).

**Comment by kitsunyan** [comment]
It will be a different application, not related to Foxy Droid at all. Just want to test things.

**Comment by kitsunyan** [comment]
[styletest-release.zip](https://github.com/kitsunyan/foxy-droid/files/4955564/styletest-release.zip)

There will be 2 toolbars. Can you show me how they look?

It's an APK file, just renamed to ZIP because github doesn't allow to upload APK files here.

**Comment by andinus** [comment]
Both bars have white-ish back arrows & only upper bar has white-ish text color, lower one is dark. Both bars have similar dark background. And upper bar text is bold, lower one is regular.

![20200722_110137](https://user-images.githubusercontent.com/62012039/88138148-a9c93180-cbdc-11ea-9af7-360876da228e.jpg)

**Comment by kitsunyan** [comment]
Ok, that's expected. Let's test some other options: [styletest-release.zip](https://github.com/kitsunyan/foxy-droid/files/4959696/styletest-release.zip)

**Comment by andinus** [comment]
There are 6 title bars, all of them have back arrows in white-ish color & dark blue-ish background, except the 5th one, it's background is gray-ish.

1st bar has text in white-ish color.

2nd, 3rd & 4th have text in dark color. 4th one seems to have some extra left-margin.


5th & 6th have the text "TitleTest" where 'Test' part is in white-ish color & rest is same dark color. 6th one has left-margin similar to 4th.

![Screenshot_20200722-170738](https://user-images.githubusercontent.com/62012039/88171979-cb8fdc00-cc0f-11ea-87c7-4e6f12ea8f97.jpg)

**Comment by kitsunyan** [comment]
Let's continue! Hope it doesn't burden you much.. [styletest-release.zip](https://github.com/kitsunyan/foxy-droid/files/4960197/styletest-release.zip)

Also, it won't work this time (meaning, there will no toolbars with correctly colored "title" text), can you extract `/system/framework/framework-res.apk` from your device to me please?

**Comment by andinus** [comment]
Ah, ok. I was just adding it as alt-text.

![Screenshot_20200722-193006](https://user-images.githubusercontent.com/62012039/88185759-d8b6c600-cc23-11ea-99f9-66415a9c7609.jpg)

**Comment by kitsunyan** [comment]
Doesn't make sense, tbh. I want to look at their `framework-res.apk`, can you give it to me?

**Comment by andinus** [comment]
That took some time to upload, here it is: https://drop.infini.fr/r/_2m4EFF5Q4#lk18ignnODiYCAKd09xEyEG6r2D9gJfPRfS5pzotfvM=

**Comment by kitsunyan** [comment]
Got it. Well, that's pathetic. This is Samsung fault, who is decided that changing default Material theme will be a good idea?..

Let's test this one. Perhaps, it will work properly this time. [styletest-release.zip](https://github.com/kitsunyan/foxy-droid/files/4961234/styletest-release.zip)

**Comment by andinus** [comment]
Oh, I see. This one shows 3 identical bars with light text on dark background.

![20200722_230157](https://user-images.githubusercontent.com/62012039/88208836-54733b80-cc41-11ea-96ef-d1c114e697e8.jpg)

**Comment by kitsunyan** [comment]
Is it possible to report the issue to Samsung? I don't like the idea of implementing such hacks in the application, tbh, but at least temporarily I will.

I added this fix in Foxy Droid, can you check it?  [foxy-droid-release.zip](https://github.com/kitsunyan/foxy-droid/files/4961706/foxy-droid-release.zip)

**Comment by andinus** [comment]
kitsunyan @ 2020-07-22 23:47 IST:

> Is it possible to report the issue to Samsung? I don't like the idea
> of implementing such hacks in the application, tbh, but at least
> temporarily I will.

I see, I'm not sure where to report this. Anyways, this is not a big
issue, can live with it.

> I added this fix in Foxy Droid, can you check it?
> [foxy-droid-release.zip](https://github.com/kitsunyan/foxy-droid/files/4961706/foxy-droid-release.zip)

Yeah, this version shows the title correctly.

**Comment by kitsunyan** [comment]
Fixed in https://github.com/kitsunyan/foxy-droid/commit/1cc79e168f8d4f6dcc8bf7d70cb05977e55f9599

**Comment by andinus** [comment]
Thank you! I'll check if it get fixed in next Samsung update & let you know.
