### ISSUE TITLE
(Feature Request) Browse apps per repo.

### ISSUE THREAD

**Issue by 5c0tt-b0t** [kitsunyan/foxy-droid#29]
Honestly guys, thank you... I love this app, best f-droid client EVER!
Just like the 'classic f-droid' interface, but quicker, prettier and I love the sort button on the top of the screen that is then available for all the categories.
Been using this app for over a month now and the only thing that I really miss from my previous client (Aurora Droid) is:
- Browse apps per repo.
(E.g search all apps from ”IzzyOnDroid's repo" etc).
Its a big time saver, I would love this to be implemented if possible.
To avoid cluttering the UI, they could be listed in the bottom of the category drop-down menu.

Thank you again for the amazing app!

**Comment by kitsunyan** [comment]
> To avoid cluttering the UI, they could be listed in the bottom of the category drop-down menu.

Yes, integrating it into the current UI will be a problem. If I place it to the bottom of the categories list, there will be no way to choose categories. Moreover, displaying available per-repo categories is also a problem, so it shouldn't work like filter, I can either allow to choose category or choose repo in this case.

**Comment by kitsunyan** [comment]
> To avoid cluttering the UI, they could be listed in the bottom of the category drop-down menu.

Yes, integrating it into the current UI will be a problem. If I place it to the bottom of the categories list, there will be no way to choose categories. Moreover, displaying available per-repo categories is also a problem, so it shouldn't work like filter, I can either allow to choose category or choose repo in this case.

**Comment by 5c0tt-b0t** [comment]
related to this, when viewing an app, its nice to see "other apps by developer" (Aurora feature) all my requests are really just suggestions, all very minor but together gives a more seamless experience, i only suggest things like this and my other feature request open (root installation) as i love his client and honestly think that everyone should be using this app instead (like i am!),  these are things that others like me (migrating from a different client) may miss/still want, this may keep them using this app instead of the others possibly as EVERYTHING else about this app is better! Its faster, app is tiny, better navigation, even though have tons of repos this syncs faster and searching is instant still! Aurora  doesnt and annoyingly shows duplicated apps if you have F-droid & F-droid archive enabled, your sorting of every category via latest, date added etc (I could keep on going why this client is the best!)
Only thing i would say is it lacks a few of the small features from some others clients (hence, my suggestions).
Just food for thought is all!
- search via repo
- see other apps by the developer
- root installation
- cant think of anything else because this app is already so close to perfection! :)

**THANK YOU!**

**Comment by kitsunyan** [comment]
Done. https://github.com/kitsunyan/foxy-droid/commit/09067cd2d4aaeb66ce448478f1da659f24bc48c3

I'm not sure it's necessary to allow to see other applications from developer. There is no such thing as "developer id" or anything, the only way to see this information is searching by name, which I don't think is a good solution. I'm also not sure how it can be integrated into current UI.

Root installation is planned, so I didn't close the related issue.
