### ISSUE TITLE
Add new/updated apps catergories

### ISSUE THREAD

**Issue by M86xKC** [kitsunyan/foxy-droid#3]
This is a feature of the official f-droid client that is missing from foxy-droid. Help in discovering new apps that have been added/updated.

**Comment by GhilbiGithubilbi** [comment]
+1, this is the most important feature for me. Good luck with the project, looks amazing!

**Comment by kitsunyan** [comment]
There will be a feature to sort by date added and last update in next version https://github.com/kitsunyan/foxy-droid/commit/561352b685dce760e6fad9fd4cca8d92af5b344a.
