### ISSUE TITLE
White flash when opening app

### ISSUE THREAD

**Issue by gokulraam** [kitsunyan/foxy-droid#31]
When opening app, it flashes white briefly until the app is opened even though dark mode is set. It didn't exist in previous version, only occurs with latest version 1.2

**Comment by kitsunyan** [comment]
I suppose this should fix the issue https://github.com/kitsunyan/foxy-droid/commit/175448dc8df7a76bd247fb78f550a32bf087c0bd

> It didn't exist in previous version

It did, but you probably didn't notice it since it may happen under various conditions.
