### ISSUE TITLE
Add option to set default tab

### ISSUE THREAD

**Issue by r-a-y** [kitsunyan/foxy-droid#33]
Hi, I just tested Foxy Droid and it is a great alternative to F-Droid. F-Droid was getting too bloated and slow and Foxy Droid loads and updates way faster!

I have one suggestion. Right now, the default tab is always set to `Available`. However, it would be great if we could have a configurable option to set it to either `Installed` or `Updates` as well.

TIA!

**Comment by kitsunyan** [comment]
Tbh, I don't like idea of multiple options when you can configure each small aspect of the application. Why would you need to change the default tab?

**Comment by r-a-y** [comment]
> Why would you need to change the default tab?

I don't like looking at the full `Available` list when I start up Foxy Droid. I'd rather have the tab set to `Updates` because I have `Sync repositories automatically` set to `Never`. That way, I can quickly hit the Sync button after Foxy Droid starts up.

**Comment by kitsunyan** [comment]
Actually, you can also easily hit "updates" after "sync", especially since syncing takes some time and these button are close to each other.
