### ISSUE TITLE
[Feature] Show Which Repo An Apk Is From

### ISSUE THREAD

**Issue by seniorm0ment** [kitsunyan/foxy-droid#39]
Suggesting implementing the ability to see what repo an app is from. Too many times I recommend someone an app, and not sure which repo it's being pulled from. Would be nice to be able to see the repo when viewing the apps page.

**Comment by kitsunyan** [comment]
You can always see the repo in package details on the bottom of application screen. I think that should be enough.

**Comment by seniorm0ment** [comment]
Where do you see package details?

**Comment by r-a-y** [comment]
With the current version of Foxy Droid, if I click on an app and look under Versions, it says `Installed` for both the F-Droid version and the alternative repo version.

The `Installed` label should only show for the version installed from the given repo. Tested with NewPipe and the [NewPipe upstream repo](https://archive.newpipe.net/fdroid/repo/).

**Comment by kitsunyan** [comment]
> Where do you see package details?

<img src="https://raw.githubusercontent.com/kitsunyan/foxy-droid/master/metadata/en-US/images/phoneScreenshots/3.png" width="320px" />

Look at "Provided by F-Droid".

> The Installed label should only show for the version installed from the given repo. Tested with NewPipe and the NewPipe upstream repo.

No, it shouldn't. It shows "installed" for both because they're the same versions, signed with the same certificate.

**Comment by seniorm0ment** [comment]
Ah ok, I see it, my bad thank you!

**Comment by r-a-y** [comment]
> No, it shouldn't. It shows "installed" for both because they're the same versions, signed with the same certificate.

Ahh, you're correct. Forget I said anything!
