### ISSUE TITLE
Option to only show F-Droid apps on Installed tab

### ISSUE THREAD

**Issue by Pentaphon** [kitsunyan/foxy-droid#41]
What the title says.

**Comment by Wilker-uwu** [comment]
additionally, it would be cool to have a filter to show all applications of any chosen repositories :3

**Comment by kitsunyan** [comment]
> What the title says.

The only way to distinguish application from F-Droid from application from other sources is comparing signatures of their APKs. But:

1. Different APKs in repo may have different signature
2. Different repositories may contain the same applications with different signatures

Moreover, comparing the signatures will require to store in database all existing signatures, which will complicate the scheme a lot.
I don't think this thing is resolvable in a sane way.

> additionally, it would be cool to have a filter to show all applications of any chosen repositories :3

You already can. This feature was added in 1.3, which wasn't added to F-Droid repository yet.

**Comment by Pentaphon** [comment]
>I don't think this thing is resolvable in a sane way.

I'll take your word for it. Just wanted to see if it were possible. Closing.

**Comment by Pentaphon** [comment]
> which wasn't added to F-Droid repository yet.

Speaking of which. My F-Droid just updated a ton of apps and Foxy Droid was nowhere in sight and it's been 9 days since you pushed 1.3. Just thought I should let you know in case there's an issue.

**Comment by kitsunyan** [comment]
Yes, I know. It happens sometimes: some successfully built APKs are not deployed into repository. Recently there were a lot of such applications https://gitlab.com/fdroid/admin/-/issues/180
This time only a few applications weren't deployed, and Foxy Droid is one of them. That's sad, but that happens.

Here is a [build activity log](https://f-droid.org/wiki/index.php?title=Special:RecentChanges&days=7&from=&hidebots=0&hideanons=1&hideliu=1&limit=500) you can check build status, and here is a [deploy activity log](https://gitlab.com/fdroid/fdroiddata/-/commits/master?search=Update+known+apks), you can monitor changes there.

**Comment by kitsunyan** [comment]
This time it failed again https://f-droid.org/wiki/page/nya.kitsunyan.foxydroid/lastbuild_4 ¯\\\_(ツ)\_/¯

**Comment by Wilker-uwu** [comment]
i just found out that this is already implemented at the bottom of the category list. could use some more visual cues though

![Screenshot of Foxy Droid showing the bottom of the categories screen](https://user-images.githubusercontent.com/10854855/90340514-1dd5da00-dfcf-11ea-840d-247b3fa4ebe3.png)

**Comment by kitsunyan** [comment]
Yes, I said about that above.

> You already can. This feature was added in 1.3, which wasn't added to F-Droid repository yet.

**Comment by Wilker-uwu** [comment]
i see. sorry ^^'
