### ISSUE TITLE
Pull down to sync

### ISSUE THREAD

**Issue by linsui** [kitsunyan/foxy-droid#46]
In `available` tab, if I want to sync repo I have to tap the three button and then sync repos . It's weird that there is a sync button on other tabs but not on `available` tab. Could you please allow pulling down to sync on all tabs?

**Comment by xxxxme** [comment]
I see a sync button on the available tab in version 1.3.
I'm against pull down to sync: it has caused me to sync many times unintentionally. ![cbb34ee0-821f-4060-be11-86e6c0da95ef](https://user-images.githubusercontent.com/3073154/90333893-8c974100-df97-11ea-946d-33c05ed73da2.jpg)

**Comment by kitsunyan** [comment]
https://github.com/kitsunyan/foxy-droid/issues/30

**Comment by linsui** [comment]
Got it. Thanks!
