### ISSUE TITLE
Option to disable full text search

### ISSUE THREAD

**Issue by CactiChameleon9** [kitsunyan/foxy-droid#48]
I often find it easier and faster to find the app I want without it, and so I preferred it before 1.3. Although, your search is still often better than fdroid's.

**Comment by kitsunyan** [comment]
Even with full text search, more relevant results are placed above less relevant ones. In fact, the search behavior didn't change between 1.2 and 1.3. In 1.3 you'll just see more results placed _to the bottom of the list_, they're not mixed so they don't make searching harder.

**Comment by CactiChameleon9** [comment]
OK, thanks that's fine then. Sorry to bother you, and thanks for making this amazing app!
