### ISSUE TITLE
Add pt_BR strings

### ISSUE THREAD

**Issue by ghost** [kitsunyan/foxy-droid#55]
Hello devs,

Here are translated strings for foxy in pt_BR.

[Foxy-droid](https://github.com/aevw/RD-pt_BR/blob/master/foxy-pt_BR.xml) 

Thanks

**Comment by kitsunyan** [comment]
Now there is an open PR for pt_BR translation, moving there https://github.com/kitsunyan/foxy-droid/pull/67.
