### ISSUE TITLE
Backup of installed apps

### ISSUE THREAD

**Issue by naoliv** [kitsunyan/foxy-droid#58]
If possible, could we have some way to backup the list of installed apps, so we could reinstall everything we had in case we need, please? (when restoring the phone or using Foxy Droid on a new device, for example).

**Comment by kitsunyan** [comment]
Is this feature somehow related to https://github.com/kitsunyan/foxy-droid/issues/43? I think implementing both will be quite overkill, especially since Foxy Droid doesn't support installing multiple applications at once yet.

**Comment by naoliv** [comment]
It's probably the same, yes.
