### ISSUE TITLE
Why Android 4.4.2 is not supported

### ISSUE THREAD

**Issue by BahrawiGuide** [kitsunyan/foxy-droid#64]
Can you help make it support Android 4.4.2

**Comment by Pentaphon** [comment]
Time for you to buy a new device...

**Comment by hockeymikey** [comment]
> Time for you to buy a new device...

Disagreed, if kitkat works for him go for it. It was the last version of Android that was actually really good. Peak UI, hands down. I would go back if I could.

**Comment by Pentaphon** [comment]
> I would go back if I could.

You can't. It's over. Time to move on. Things will keep changing even after 11. Developers shouldn't have to support 4.x forever.

**Comment by hockeymikey** [comment]
> You can't. It's over. 

No it's not, KK still works fine.

>Time to move on. Things will keep changing even after 11. 

Negatively. Sometimes you need to go your own way, blaze a new trail.

>Developers shouldn't have to support 4.x forever.

It's not hard supporting old version, lol. Just use the support libraries they already do, add some version checks in there for new APIs that'll crash stuff if called that don't have support. It's not hard.

**Comment by AlbahrawyAlalimi** [comment]
> Time for you to buy a new device...
Why do I need to change my phone ?!As long as it works fine and there are no errors in this Android version it is perfect for me.

**Comment by BahrawiGuide** [comment]
@Pentaphon Why do I need to change my phone ?!As long as it works fine and there are no errors in this Android version it is perfect for me.

**Comment by Pentaphon** [comment]
> Why do I need to change my phone ?

Because I don't think the dev is going to roll back support just for you.

**Comment by kitsunyan** [comment]
I don't want to bring AppCompat library into the project to support older Android versions. There are a lot of architectural differences between 4.4 and 5.0 to start a new project in 2020 with 4.4 support in mind. I'm sorry, 4.4 won't be supported.

**Comment by Pentaphon** [comment]
>  Sometimes you need to go your own way, blaze a new trail.

Sometimes, you need to buy a new phone. The dev has spoken.

**Comment by hockeymikey** [comment]
@Pentaphon Or sometimes you need to fork and make the changes that others are unwilling to do.

**Comment by Pentaphon** [comment]
> Or sometimes you need to fork and make the changes that others are unwilling to do.

Go for it.
