### ISSUE TITLE
Rollback to an older version without uninstalling the current one

### ISSUE THREAD

**Issue by pwdbyEXT** [kitsunyan/foxy-droid#77]
As title says, downgrade to an older version without uninstalling the newer one and loosing all configuration. This would be extremely useful when a broken update is released, like the recent Termux one.
![Screenshot_2021-01-31-18-30-30-127_nya kitsunyan foxydroid](https://user-images.githubusercontent.com/35818838/106390745-86d0d300-63f2-11eb-8b31-dfddc9f8dcb7.jpg)

**Comment by kitsunyan** [comment]
> downgrade to an older version without uninstalling the newer one and loosing all configuration

It's impossible. Not under Android restrictions at least.

**Comment by pwdbyEXT** [comment]
> It's impossible. Not under Android restrictions at least.

Yes. I remember it being a feature in the official app. I installed to recheck and the "downgrade" button is still there but returns an "unknown error" upon installation.
It's unfortunate how something that useful is no longer allowed.
Thank you for the fast reply.
This is a great app, I appreciate your effort.
