### ISSUE TITLE
Suggestion : favorites

### ISSUE THREAD

**Issue by iiitomo** [kitsunyan/foxy-droid#79]
Again, thx for FoxyDroid, I love it.
Here is a suggestion for a feature, that I think is missing in all f-droid clients.

I like to test new apps, so I often install, test and immediately uninstall.
The ones I like most, I wish I could tag them in FoxyDroid as 'favorites', so that I can find them easily in the future (e.g. for a new test).

There may be several ways to implement that feature, but I think this could be done via a Star icon that could be toggled in the app page, and adding a 'Favorites' entry in the category list of the 'Available' tab.

Thx for reading

**Comment by kitsunyan** [comment]
https://github.com/kitsunyan/foxy-droid/issues/43
