### ISSUE TITLE
Feature request: Add the ability to download apps through Tor 

### ISSUE THREAD

**Issue by ghost** [kitsunyan/foxy-droid#81]
I would like the ability to download apps through Tor 
![Screenshot_20210215-163757_1](https://user-images.githubusercontent.com/78061111/107995726-c8de4500-6fac-11eb-9150-e48999dd496a.png)

**Comment by kitsunyan** [comment]
You already can. Just configure proxy settings to use tor, like 127.0.0.1:9050.
