### ISSUE TITLE
(Feature Request) Latest updated and new apps lists

### ISSUE THREAD

**Issue by salazarsalsasauce** [kitsunyan/foxy-droid#9]
This is the best f-droid client app so far. Fast, simple, usefull... Only 2 important things are missing; latest and new apps lists. Please consider adding these lists to the app. That would make this client perfect! Thank you!

**Comment by nolda** [comment]
+1

**Comment by Spielmops** [comment]
+1

**Comment by OliverLew** [comment]
I think the commit https://github.com/kitsunyan/foxy-droid/commit/561352b685dce760e6fad9fd4cca8d92af5b344a did exactly the two things. We maybe simply need a new release.

**Comment by kitsunyan** [comment]
https://github.com/kitsunyan/foxy-droid/issues/3
